server:
  port: 8083
  servlet:
    context-path: /springboot_all
spring:
  rabbitmq:
    username: admin
    password: admin
    host: 192.168.1.123
    port: 5672
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: 1804a